version: "3.7"
services:
  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: modulesapp
    container_name: modulesapp-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - modulesapp

  db:
    image: mysql:8.0
    container_name: modulesapp-db
    restart: unless-stopped
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d
      - ${MYSQL_DATA_DIR-./storage/data/mysql}:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./storage/logs/mysql}:/var/log/mysql
    networks:
      - modulesapp

  nginx:
    image: nginx:alpine
    container_name: modulesapp-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    networks:
      - modulesapp
  redis:
    image: redis:latest
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - ./docker/redis:/data
    restart: unless-stopped
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - modulesapp
    healthcheck:
      test: [ "CMD","redis-cli","ping" ]
      interval: 600s
      timeout: 10s
      retries: 5

networks:
  modulesapp:
    driver: bridge
